/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aixtor.intranet.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LeaveTracker service. Represents a row in the &quot;INTRANET_LeaveTracker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aixtor.intranet.model.impl.LeaveTrackerModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aixtor.intranet.model.impl.LeaveTrackerImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LeaveTracker
 * @generated
 */
@ProviderType
public interface LeaveTrackerModel
	extends BaseModel<LeaveTracker>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave tracker model instance should use the {@link LeaveTracker} interface instead.
	 */

	/**
	 * Returns the primary key of this leave tracker.
	 *
	 * @return the primary key of this leave tracker
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave tracker.
	 *
	 * @param primaryKey the primary key of this leave tracker
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the leave tracker ID of this leave tracker.
	 *
	 * @return the leave tracker ID of this leave tracker
	 */
	public long getLeaveTrackerId();

	/**
	 * Sets the leave tracker ID of this leave tracker.
	 *
	 * @param leaveTrackerId the leave tracker ID of this leave tracker
	 */
	public void setLeaveTrackerId(long leaveTrackerId);

	/**
	 * Returns the user ID of this leave tracker.
	 *
	 * @return the user ID of this leave tracker
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this leave tracker.
	 *
	 * @param userId the user ID of this leave tracker
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave tracker.
	 *
	 * @return the user uuid of this leave tracker
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this leave tracker.
	 *
	 * @param userUuid the user uuid of this leave tracker
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the total compen of this leave tracker.
	 *
	 * @return the total compen of this leave tracker
	 */
	public int getTotalCompen();

	/**
	 * Sets the total compen of this leave tracker.
	 *
	 * @param totalCompen the total compen of this leave tracker
	 */
	public void setTotalCompen(int totalCompen);

	/**
	 * Returns the booked compen of this leave tracker.
	 *
	 * @return the booked compen of this leave tracker
	 */
	public int getBookedCompen();

	/**
	 * Sets the booked compen of this leave tracker.
	 *
	 * @param bookedCompen the booked compen of this leave tracker
	 */
	public void setBookedCompen(int bookedCompen);

	/**
	 * Returns the total earned of this leave tracker.
	 *
	 * @return the total earned of this leave tracker
	 */
	public int getTotalEarned();

	/**
	 * Sets the total earned of this leave tracker.
	 *
	 * @param totalEarned the total earned of this leave tracker
	 */
	public void setTotalEarned(int totalEarned);

	/**
	 * Returns the booked earned of this leave tracker.
	 *
	 * @return the booked earned of this leave tracker
	 */
	public int getBookedEarned();

	/**
	 * Sets the booked earned of this leave tracker.
	 *
	 * @param bookedEarned the booked earned of this leave tracker
	 */
	public void setBookedEarned(int bookedEarned);

	/**
	 * Returns the total floater of this leave tracker.
	 *
	 * @return the total floater of this leave tracker
	 */
	public int getTotalFloater();

	/**
	 * Sets the total floater of this leave tracker.
	 *
	 * @param totalFloater the total floater of this leave tracker
	 */
	public void setTotalFloater(int totalFloater);

	/**
	 * Returns the booked floater of this leave tracker.
	 *
	 * @return the booked floater of this leave tracker
	 */
	public int getBookedFloater();

	/**
	 * Sets the booked floater of this leave tracker.
	 *
	 * @param bookedFloater the booked floater of this leave tracker
	 */
	public void setBookedFloater(int bookedFloater);

	/**
	 * Returns the total unpaid of this leave tracker.
	 *
	 * @return the total unpaid of this leave tracker
	 */
	public int getTotalUnpaid();

	/**
	 * Sets the total unpaid of this leave tracker.
	 *
	 * @param totalUnpaid the total unpaid of this leave tracker
	 */
	public void setTotalUnpaid(int totalUnpaid);

	/**
	 * Returns the booked unpaid of this leave tracker.
	 *
	 * @return the booked unpaid of this leave tracker
	 */
	public int getBookedUnpaid();

	/**
	 * Sets the booked unpaid of this leave tracker.
	 *
	 * @param bookedUnpaid the booked unpaid of this leave tracker
	 */
	public void setBookedUnpaid(int bookedUnpaid);

	/**
	 * Returns the create date of this leave tracker.
	 *
	 * @return the create date of this leave tracker
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave tracker.
	 *
	 * @param createDate the create date of this leave tracker
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the created by of this leave tracker.
	 *
	 * @return the created by of this leave tracker
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this leave tracker.
	 *
	 * @param createdBy the created by of this leave tracker
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified date of this leave tracker.
	 *
	 * @return the modified date of this leave tracker
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave tracker.
	 *
	 * @param modifiedDate the modified date of this leave tracker
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this leave tracker.
	 *
	 * @return the modified by of this leave tracker
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this leave tracker.
	 *
	 * @param modifiedBy the modified by of this leave tracker
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the group ID of this leave tracker.
	 *
	 * @return the group ID of this leave tracker
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this leave tracker.
	 *
	 * @param groupId the group ID of this leave tracker
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave tracker.
	 *
	 * @return the company ID of this leave tracker
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave tracker.
	 *
	 * @param companyId the company ID of this leave tracker
	 */
	@Override
	public void setCompanyId(long companyId);

	@Override
	public LeaveTracker cloneWithOriginalValues();

}