/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.aixtor.intranet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the leave service. Represents a row in the &quot;INTRANET_leave&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.aixtor.intranet.model.impl.leaveModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.aixtor.intranet.model.impl.leaveImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see leave
 * @generated
 */
@ProviderType
public interface leaveModel
	extends BaseModel<leave>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a leave model instance should use the {@link leave} interface instead.
	 */

	/**
	 * Returns the primary key of this leave.
	 *
	 * @return the primary key of this leave
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this leave.
	 *
	 * @param primaryKey the primary key of this leave
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this leave.
	 *
	 * @return the uuid of this leave
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this leave.
	 *
	 * @param uuid the uuid of this leave
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the leave ID of this leave.
	 *
	 * @return the leave ID of this leave
	 */
	public long getLeaveId();

	/**
	 * Sets the leave ID of this leave.
	 *
	 * @param leaveId the leave ID of this leave
	 */
	public void setLeaveId(long leaveId);

	/**
	 * Returns the group ID of this leave.
	 *
	 * @return the group ID of this leave
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this leave.
	 *
	 * @param groupId the group ID of this leave
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this leave.
	 *
	 * @return the company ID of this leave
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this leave.
	 *
	 * @param companyId the company ID of this leave
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this leave.
	 *
	 * @return the user ID of this leave
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this leave.
	 *
	 * @param userId the user ID of this leave
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this leave.
	 *
	 * @return the user uuid of this leave
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this leave.
	 *
	 * @param userUuid the user uuid of this leave
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this leave.
	 *
	 * @return the user name of this leave
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this leave.
	 *
	 * @param userName the user name of this leave
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this leave.
	 *
	 * @return the create date of this leave
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this leave.
	 *
	 * @param createDate the create date of this leave
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this leave.
	 *
	 * @return the modified date of this leave
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this leave.
	 *
	 * @param modifiedDate the modified date of this leave
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the employee name of this leave.
	 *
	 * @return the employee name of this leave
	 */
	@AutoEscape
	public String getEmployeeName();

	/**
	 * Sets the employee name of this leave.
	 *
	 * @param employeeName the employee name of this leave
	 */
	public void setEmployeeName(String employeeName);

	/**
	 * Returns the leave type of this leave.
	 *
	 * @return the leave type of this leave
	 */
	@AutoEscape
	public String getLeaveType();

	/**
	 * Sets the leave type of this leave.
	 *
	 * @param leaveType the leave type of this leave
	 */
	public void setLeaveType(String leaveType);

	/**
	 * Returns the from date of this leave.
	 *
	 * @return the from date of this leave
	 */
	@AutoEscape
	public String getFromDate();

	/**
	 * Sets the from date of this leave.
	 *
	 * @param fromDate the from date of this leave
	 */
	public void setFromDate(String fromDate);

	/**
	 * Returns the to date of this leave.
	 *
	 * @return the to date of this leave
	 */
	@AutoEscape
	public String getToDate();

	/**
	 * Sets the to date of this leave.
	 *
	 * @param toDate the to date of this leave
	 */
	public void setToDate(String toDate);

	/**
	 * Returns the day type of this leave.
	 *
	 * @return the day type of this leave
	 */
	@AutoEscape
	public String getDayType();

	/**
	 * Sets the day type of this leave.
	 *
	 * @param dayType the day type of this leave
	 */
	public void setDayType(String dayType);

	/**
	 * Returns the half type of this leave.
	 *
	 * @return the half type of this leave
	 */
	@AutoEscape
	public String getHalfType();

	/**
	 * Sets the half type of this leave.
	 *
	 * @param halfType the half type of this leave
	 */
	public void setHalfType(String halfType);

	/**
	 * Returns the team email of this leave.
	 *
	 * @return the team email of this leave
	 */
	@AutoEscape
	public String getTeamEmail();

	/**
	 * Sets the team email of this leave.
	 *
	 * @param teamEmail the team email of this leave
	 */
	public void setTeamEmail(String teamEmail);

	/**
	 * Returns the reason of this leave.
	 *
	 * @return the reason of this leave
	 */
	@AutoEscape
	public String getReason();

	/**
	 * Sets the reason of this leave.
	 *
	 * @param reason the reason of this leave
	 */
	public void setReason(String reason);

	/**
	 * Returns the status of this leave.
	 *
	 * @return the status of this leave
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this leave.
	 *
	 * @param status the status of this leave
	 */
	public void setStatus(String status);

	@Override
	public leave cloneWithOriginalValues();

}